# Generated by Django 4.2.16 on 2026-01-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microempresas', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('admin_empresa', 'Administrador de Empresa'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('microempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_internos', to='microempresas.microempresa')),
            ],
            options={
                'db_table': 'usuarios_internos',
                'unique_together': {('microempresa', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('venta', 'Venta Realizada'), ('nuevo_cliente', 'Nuevo Cliente'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('microempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='microempresas.microempresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='authentication.usuariointerno')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
    ]
