# Generated by Django 4.2.16 on 2026-01-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microempresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rubro', models.CharField(blank=True, max_length=50, null=True)),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium')], default='basico', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('logo', models.CharField(default='🏪', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Microempresa',
                'verbose_name_plural': 'Microempresas',
                'db_table': 'microempresas',
            },
        ),
    ]
