# Generated by Django 4.2.16 on 2026-01-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microempresas', '0002_cliente_compra_plan_venta_proveedor_detalleventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microempresa',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='microempresa',
            name='reset_password_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
