# Generated by Django 4.2.16 on 2026-01-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microempresas', '0003_microempresa_reset_password_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=29.0, max_digits=10)),
                ('microempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_upgrade', to='microempresas.microempresa')),
            ],
            options={
                'db_table': 'solicitudes_upgrade',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
