# Generated by Django 4.2.16 on 2026-01-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microempresas', '0004_solicitudupgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudupgrade',
            name='metodo_pago',
            field=models.CharField(choices=[('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='qr', max_length=20),
        ),
    ]
