# Generated by Django 4.2.16 on 2026-01-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microempresas', '0005_solicitudupgrade_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudupgrade',
            name='metodo_pago',
            field=models.CharField(choices=[('qr', 'QR / Transferencia'), ('tarjeta', 'Tarjeta')], default='qr', max_length=20),
        ),
    ]
