# Generated by Django 4.2.16 on 2026-01-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microempresas', '0006_alter_solicitudupgrade_metodo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cliente',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reset_password_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('vendedor', 'Vendedor/Empleado'), ('comprador', 'Cliente Comprador')], default='comprador', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
