# Generated by Django 4.2.16 on 2026-01-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_password_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
